// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:raagaflow/shared/models/playlist_model.dart';
import 'package:raagaflow/shared/models/track_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PlaylistModelAdapter());
    registerAdapter(TrackModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PlaylistModelAdapter());
    registerAdapter(TrackModelAdapter());
  }
}
