const Map<String, Map<String, List<String>>> moodMap = {
  'hindi': {
    'udaas': ['sad hindi songs', 'dard bhari', 'bewafa songs', 'judai songs'],
    'khush': ['happy hindi songs', 'celebration songs hindi', 'khushi wale gaane'],
    'gym': ['gym motivation hindi', 'workout songs bollywood', 'power songs hindi'],
    'bhakti': ['bhajan aarti', 'devotional hindi songs', 'mantra meditation'],
    'drive': ['road trip hindi songs', 'long drive gaane', 'car songs bollywood'],
    'neend': ['lullaby hindi', 'soothing hindi songs', 'raat ke gaane peaceful'],
    'pyaar': ['romantic hindi songs', 'love songs bollywood', 'ishq pyaar songs'],
    'party': ['party songs hindi', 'dance bollywood', 'dj remix hindi'],
    'study': ['lofi hindi', 'instrumental bollywood', 'focus music hindi'],
    'chill': ['chill hindi songs', 'mellow hindi', 'acoustic hindi'],
    'barish': ['barish songs hindi', 'rain songs bollywood', 'monsoon hindi'],
    'subah': ['morning songs hindi', 'fresh start hindi', 'peaceful morning music'],
  },
  'tamil': {
    'udaas': ['sad tamil songs', 'tamil kadhal songs', 'anirudh sad'],
    'khush': ['happy tamil songs', 'kuthu songs', 'jolly tamil'],
    'gym': ['workout tamil songs', 'mass bgm tamil', 'energy tamil'],
    'bhakti': ['tamil devotional songs', 'murugan songs', 'ayyappan songs'],
    'drive': ['long drive tamil songs', 'car songs kollywood'],
    'neend': ['lullaby tamil', 'peaceful tamil songs', 'sleep tamil music'],
    'pyaar': ['love songs tamil', 'romantic kollywood', 'ar rahman love'],
    'party': ['dance songs tamil', 'dj remix tamil', 'kuthu paatu'],
    'study': ['lofi tamil', 'instrumental tamil', 'ar rahman instrumental'],
    'chill': ['chill tamil', 'melody tamil', 'soft tamil songs'],
    'barish': ['rain songs tamil', 'mazhai songs'],
    'subah': ['morning raga tamil', 'carnatic morning', 'suprabhatam'],
  },
  'telugu': {
    'udaas': ['sad telugu songs', 'telugu love failure songs'],
    'khush': ['happy telugu songs', 'mass songs telugu'],
    'gym': ['gym songs telugu', 'power songs tollywood'],
    'bhakti': ['telugu devotional songs', 'venkateswara songs'],
    'drive': ['long drive telugu songs', 'road trip tollywood'],
    'neend': ['sleep songs telugu', 'lullaby telugu'],
    'pyaar': ['romantic telugu songs', 'love songs tollywood'],
    'party': ['dance songs telugu', 'dj telugu songs'],
    'study': ['lofi telugu', 'instrumental telugu', 'focus music telugu'],
    'chill': ['melody telugu songs', 'soft telugu songs'],
    'barish': ['rain songs telugu', 'varsham songs'],
    'subah': ['morning songs telugu', 'suprabhatam telugu'],
  },
  'kannada': {
    'udaas': ['sad kannada songs', 'kannada love failure'],
    'khush': ['happy kannada songs', 'jolly kannada'],
    'gym': ['mass kannada songs', 'workout kannada'],
    'bhakti': ['kannada devotional songs', 'dasara songs kannada'],
    'pyaar': ['romantic kannada songs', 'love songs sandalwood'],
    'party': ['dance kannada songs', 'kuthu kannada'],
    'study': ['lofi kannada', 'instrumental kannada'],
    'chill': ['melody kannada', 'soft kannada songs'],
  },
  'malayalam': {
    'udaas': ['sad malayalam songs', 'malayalam love failure'],
    'khush': ['happy malayalam songs', 'fun malayalam'],
    'gym': ['mass malayalam songs', 'workout malayalam'],
    'bhakti': ['malayalam devotional songs', 'ayyappa songs malayalam'],
    'pyaar': ['romantic malayalam songs', 'love songs mollywood'],
    'party': ['dance songs malayalam', 'dj malayalam'],
    'study': ['lofi malayalam', 'instrumental malayalam'],
    'chill': ['melody malayalam', 'soft malayalam songs'],
  },
  'punjabi': {
    'udaas': ['sad punjabi songs', 'punjabi dard songs'],
    'khush': ['happy punjabi songs', 'bhangra songs'],
    'gym': ['gym punjabi songs', 'workout bhangra'],
    'bhakti': ['punjabi devotional songs', 'gurbani shabad'],
    'drive': ['long drive punjabi songs', 'road trip punjabi'],
    'pyaar': ['romantic punjabi songs', 'love songs punjabi'],
    'party': ['party punjabi songs', 'dj punjabi remix'],
    'chill': ['chill punjabi songs', 'soft punjabi'],
  },
};

const Map<String, String> englishToMoodKey = {
  'sad': 'udaas',
  'happy': 'khush',
  'gym': 'gym',
  'spiritual': 'bhakti',
  'devotional': 'bhakti',
  'drive': 'drive',
  'sleep': 'neend',
  'love': 'pyaar',
  'party': 'party',
  'study': 'study',
  'chill': 'chill',
  'rain': 'barish',
  'morning': 'subah',
  'workout': 'gym',
  'romantic': 'pyaar',
  'focus': 'study',
};
